# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/debian/LinuxDrivers_feature

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/debian/LinuxDrivers_feature

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/debian/LinuxDrivers_feature/CMakeFiles /home/debian/LinuxDrivers_feature/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/debian/LinuxDrivers_feature/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named backsub_test

# Build rule for target.
backsub_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 backsub_test
.PHONY : backsub_test

# fast build rule for target.
backsub_test/fast:
	$(MAKE) -f CMakeFiles/backsub_test.dir/build.make CMakeFiles/backsub_test.dir/build
.PHONY : backsub_test/fast

axidma.o: axidma.c.o

.PHONY : axidma.o

# target to build an object file
axidma.c.o:
	$(MAKE) -f CMakeFiles/backsub_test.dir/build.make CMakeFiles/backsub_test.dir/axidma.c.o
.PHONY : axidma.c.o

axidma.i: axidma.c.i

.PHONY : axidma.i

# target to preprocess a source file
axidma.c.i:
	$(MAKE) -f CMakeFiles/backsub_test.dir/build.make CMakeFiles/backsub_test.dir/axidma.c.i
.PHONY : axidma.c.i

axidma.s: axidma.c.s

.PHONY : axidma.s

# target to generate assembly for a file
axidma.c.s:
	$(MAKE) -f CMakeFiles/backsub_test.dir/build.make CMakeFiles/backsub_test.dir/axidma.c.s
.PHONY : axidma.c.s

drivers/xbacksub.o: drivers/xbacksub.c.o

.PHONY : drivers/xbacksub.o

# target to build an object file
drivers/xbacksub.c.o:
	$(MAKE) -f CMakeFiles/backsub_test.dir/build.make CMakeFiles/backsub_test.dir/drivers/xbacksub.c.o
.PHONY : drivers/xbacksub.c.o

drivers/xbacksub.i: drivers/xbacksub.c.i

.PHONY : drivers/xbacksub.i

# target to preprocess a source file
drivers/xbacksub.c.i:
	$(MAKE) -f CMakeFiles/backsub_test.dir/build.make CMakeFiles/backsub_test.dir/drivers/xbacksub.c.i
.PHONY : drivers/xbacksub.c.i

drivers/xbacksub.s: drivers/xbacksub.c.s

.PHONY : drivers/xbacksub.s

# target to generate assembly for a file
drivers/xbacksub.c.s:
	$(MAKE) -f CMakeFiles/backsub_test.dir/build.make CMakeFiles/backsub_test.dir/drivers/xbacksub.c.s
.PHONY : drivers/xbacksub.c.s

feature.o: feature.cpp.o

.PHONY : feature.o

# target to build an object file
feature.cpp.o:
	$(MAKE) -f CMakeFiles/backsub_test.dir/build.make CMakeFiles/backsub_test.dir/feature.cpp.o
.PHONY : feature.cpp.o

feature.i: feature.cpp.i

.PHONY : feature.i

# target to preprocess a source file
feature.cpp.i:
	$(MAKE) -f CMakeFiles/backsub_test.dir/build.make CMakeFiles/backsub_test.dir/feature.cpp.i
.PHONY : feature.cpp.i

feature.s: feature.cpp.s

.PHONY : feature.s

# target to generate assembly for a file
feature.cpp.s:
	$(MAKE) -f CMakeFiles/backsub_test.dir/build.make CMakeFiles/backsub_test.dir/feature.cpp.s
.PHONY : feature.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... backsub_test"
	@echo "... axidma.o"
	@echo "... axidma.i"
	@echo "... axidma.s"
	@echo "... drivers/xbacksub.o"
	@echo "... drivers/xbacksub.i"
	@echo "... drivers/xbacksub.s"
	@echo "... feature.o"
	@echo "... feature.i"
	@echo "... feature.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

